name: build-mingw13
on: push
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: mingw
      shell: cmd
      run: |
        set PATH=C:\mingw1310_64\bin;C:\Program Files\7-Zip;%PATH%
        if exist C:\mingw1310_64\bin\gcc.exe goto mingw_end
        if not exist winlibs-x86_64-posix-seh-gcc-13.1.0-mingw-w64ucrt-11.0.0-r5.7z (
            echo downloading winlibs-x86_64-posix-seh-gcc-13.1.0-mingw-w64ucrt-11.0.0-r5.7z
            curl -L -o winlibs-x86_64-posix-seh-gcc-13.1.0-mingw-w64ucrt-11.0.0-r5.7z https://github.com/brechtsanders/winlibs_mingw/releases/download/13.1.0-16.0.5-11.0.0-ucrt-r5/winlibs-x86_64-posix-seh-gcc-13.1.0-mingw-w64ucrt-11.0.0-r5.7z
        )
        7z rn winlibs-x86_64-posix-seh-gcc-13.1.0-mingw-w64ucrt-11.0.0-r5.7z mingw64 mingw1310_64
        if not exist C:\mingw1310_64\bin\gcc.exe 7z x -y -oC:\ winlibs-x86_64-posix-seh-gcc-13.1.0-mingw-w64ucrt-11.0.0-r5.7z
        :mingw_end
    - name: qt
      shell: cmd
      run: |
        set PATH=C:\Program Files\7-Zip;%PATH%
        if exist C:\Qt\6.10.0\mingw_64\bin\qmake.exe goto qt_end
        if not exist Qt-6.10.0-mingw13.7z (
            echo downloading Qt-6.10.0-mingw13.7z
            curl -L -o Qt-6.10.0-mingw13.7z https://github.com/mugiseyebrows/build-qt/releases/download/6.10.0/Qt-6.10.0-mingw13.7z
        )
        7z x -y -oC:\Qt\6.10.0 Qt-6.10.0-mingw13.7z
        :qt_end
    - name: source
      shell: cmd
      run: |
        set PATH=C:\Program Files\Git\cmd;%PATH%
        if exist "C:\Program Files\Git\usr\bin\patch.exe" set PATCH=C:\Program Files\Git\usr\bin\patch.exe
        if not defined PATCH (
        echo PATCH not found
        exit /b
        )
        set PATCH=C:\Program Files\Git\usr\bin\patch.exe
        if not exist qwt git clone -b qwt-6.3 https://git.code.sf.net/p/qwt/git qwt
        pushd qwt
            "%PATCH%" -N -i ../0001-QWT_INSTALL_PREFIX.patch
            "%PATCH%" -N -i ../0001-no-examples.patch
            "%PATCH%" -N -i ../0001-release-build.patch
        popd
    - name: build
      shell: cmd
      run: |
        set PATH=C:\Qt\6.10.0\mingw_64\bin;%PATH%
        pushd qwt
            qmake
            mingw32-make
            mingw32-make install
        popd
    - name: main
      shell: cmd
      run: |
        set PATH=C:\Program Files\7-Zip;%PATH%
        7z a -y Qwt-6.3.1-Qt-6.10.0-mingw13.7z C:\Qwt-6.3.1-Qt-6.10.0
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: Qwt-6.3.1-Qt-6.10.0
        path: C:\Qwt-6.3.1-Qt-6.10.0
    - name: release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Qwt-6.3.1-Qt-6.10.0-mingw13.7z
